<a href="https://colab.research.google.com/github/SiwakornEDZ/mllab-python/blob/main/mllab01_intro_pyhon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Machine Learning Lab Practical 1 - Basic Python (21/07/2023)

ชื่อ นายเจษฎา เพ็งสุวรรณ

รหัสนักศึกษา 0000000

e-mail jedsada.phengsuwan@gmail.com

# Lab Practical Guideline


**วัตถุประสงค์**

1. เพื่อเรียนรู้การเขียนโปรแกรมภาษา Python เบื้องต้น
2. เพื่อเรียนรู้การใช้งาน Numpy library
3. สร้างความคุ้นเคยการเขียนโปรแกรมภาษา Python

**ขั้นตอนการฝึกปฏิบัติการ**

1. สร้างเอกสารบน colab และตั้งชื่อไฟล์เป็น 'mllab01-intro_pyhon.ipynb'
2. สร้างหัวเอกสาร ใส่ชื่อ รหัส นศ. และ e-mail ของตนเอง โดยดูตามเอกสารตัวอย่างเพจนี้
3. ศึกษาและทดลองการใช้งานภาษา Python เบื้องต้น และ Numpy ตามเอกสารตัวอย่างเพจนี้
3. ศึกษาการการใช้งานภาษา Python และ Numpy จากเว็บไซต์ [w3Schools.com](https://www.w3schools.com/python/default.asp)

**การส่งผลงาน**
1. ให้ share เอกสารที่ นศ. ทำมายัง อาจารย์ผู้สอน และผู้ช่วยสอน e-mail jedsada.phengsuwan@gmail.com และ jerayu.k@en.rmutt.ac.th  *โดยกำหนดสิทธิ์เป็น Commenter*  [ดูตัวอย่าง](https://raw.githubusercontent.com/phengsuwan/ML04622316/f9e6a12ea0521de9ee991aeb3813b306ae6c8013/figures/submit.png)
2. เพิ่ม link ผลงานเข้าไปในหน้า Profile ของตนเอง
3. กำหนดส่งภายใน วันจันทร์ 24/07/2023 23.59



# 1. พื้นฐานภาษา Python

> 1.1 คำสั่งพื้นฐาน

1.1.1 การแสดงข้อความ​ -- Python **คำสั่งแรกของฉัน**


In [ ]:
print("Hello World")

1.1.2 การตรวจสอบเวอร์ชั่นของ Python


*   สัหญลักษณ์ `#` ใช้ในการเขียน comment ใน code python
*   `import` เป็นการเรียกใช้งาน library



In [ ]:
# เรียกใช้งาน library sys
import sys
print(sys.version)

1.1.3 การประกาศตัวแปรและแสดงผลค่าตัวแปร  

*   อ่านเพิ่มเติมเกี่ยวกับการใช้งานตัวแปร [link1](https://www.w3schools.com/python/python_variables.asp) และ [link2](https://www.w3schools.com/python/python_variables_output.asp)
*   ประเภทของตัวแปรพื้นฐานในภาษา Python [link](https://www.w3schools.com/python/python_datatypes.asp)


In [ ]:
x = 5
y = "John"

# แสดงข้อมูลในตัวแปร
print(x)
print(y)

# แสดงประเภทของตัวแปร
x = 1    # int
y = 2.8  # float
z = 1j   # complex
print(type(x))
print(type(y))
print(type(z))


1.1.4 ตัวแปรประเภท string


*   อ่านเพิ่มเติม [link](https://www.w3schools.com/python/python_strings.asp)
*   รวม method การจัดการข้อมูล string [link](https://www.w3schools.com/python/python_strings_methods.asp)



In [ ]:
b = "Hello, World!"
print(b)
print(b[2:5])
print(b[2:])
print(b[:5])


1.1.5 Python Operator [link](https://www.w3schools.com/python/python_operators.asp)

In [ ]:
a = 2+5*12-9/3
b = (2+5)*((12-9)/3)
print(a)
print(b)

> 1.2 Data Structure: List, และ Dictionaries


*   เรียนรู้การเก็บข้อมูลเพิ่มเติม รวมถึงโครงสร้างแบบอื่นๆ ได้จาก [List](https://www.w3schools.com/python/python_lists.asp), [Tuple](https://www.w3schools.com/python/python_tuples.asp), [Set](https://www.w3schools.com/python/python_sets.asp), และ [Dictionaries](https://www.w3schools.com/python/python_dictionaries.asp)



1.2.1 การใช้งาน List เบื้องต้น

วัตถุประสงค์หลัก -- เพื่อเก็บค่าข้อมูลหรือตัวแปรหลายๆ ตัว ในรูปแบบ array

In [ ]:
# code ตัวอย่างการประการตัวแปร List และการเข้าถึงค่าข้อมูลมายใน List
fruits = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(fruits)
print(fruits[1])
print(fruits[-1])
print(fruits[-2])
print(fruits[2:5])
print(fruits[2:])
print(fruits[:5])

1.2.2 การวนลูปแสดงค่าใน List

In [ ]:
thislist = ["apple", "banana", "cherry"]
for x in thislist:
  print(x)

1.2.3 การเปรียบเทียบค่าในตัวแปร List


*   ให้ นศ. ดูและเปรียบเทียบวิธีการวนลูป



In [ ]:
# ตัวอย่างการเปรียบเทียบแบบที่ 1
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:        # ตรวจสอบว่า string ในตัวแปร x มีตัวอักษร 'a' อยู่หรือไม่
    newlist.append(x) # หากเป็นจริงให้เพิ่มค่าใน ตัวแปร x ลงใน newlist

print(newlist)

# ตัวอย่างการเปรียบเทียบแบบที่ 2 ** การเขียน code แบบย่อ
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]

newlist = [x for x in fruits if "a" in x]

print(newlist)

1.2.4 Dictionaries ใช้สำหรับการเก็บข้อมูลในรูปแบบ key-value pairs [link](https://www.w3schools.com/python/python_dictionaries.asp)

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)
print(thisdict["brand"])

# การเข้าถึง keys
keys = thisdict.keys()
print(f"keys - {keys}")

# การเปลี่ยนแปลงค่าในคัวแปร
thisdict["year"] = 2018
print(thisdict)

thisdict.update({"year": 2020})
print(thisdict)


> 1.3 การตรวจสอบเงื่อนไขและการวนลูป


*   เรียนรู้การใช้ If...Else
*   เรียนรู้การวนลูป For




1.3.1 การใช้งาน If...Else [link](https://www.w3schools.com/python/python_conditions.asp)


*   ให้ นศ. ทดลองเปลี่ยนค่าตัวแปร และรันใหม่



In [ ]:
# รูปแบบ if เบื้องต้น (ไม่มี else)
a = 33
b = 200
if b > a:
  print("b is greater than a")


# รูปแบบ if...else แบบสมบูรณ์
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

1.3.2 การใช้งานลูป For [link](https://www.w3schools.com/python/python_for_loops.asp)

*   ให้ นศ. ทดลองรันและสังเกตุผลลัพท์



In [ ]:
for x in "banana":
  print(x)

In [ ]:
# ตัวอย่างการใช้ range
for x in range(6):
  print(x)

In [ ]:
# ตัวอย่างการใช้ range
for x in range(2, 6):
  print(x)

> 1.4 ศึกษาเพิ่มเติม

*   ให้ นศ. เขียนตัวอย่าง code ที่ศึกษาด้วยตัวเองเพิ่มเติม อย่างน้อย 5 ตัวอย่าง



1.4.1 ตัวอย่างที่ 1 if... [เรียนรู้จาก](https://www.w3schools.com/python/python_conditions.asp)

In [ ]:
# ใส่ตัวอย่าง code ที่ได้เรียนรู้
a = 33
b = 200
if b > a:
  print("b is greater than a")

1.4.2 ตัวอย่างที่ 2 <ใส่หัวข้อ> [เรียนรู้จาก](<ใส่ URL>)

In [ ]:
# ใส่ตัวอย่าง code ที่ได้เรียนรู้

1.4.3 ตัวอย่างที่ 3 <ใส่หัวข้อ> [เรียนรู้จาก](<ใส่ URL>)

In [ ]:
# ใส่ตัวอย่าง code ที่ได้เรียนรู้

1.4.4 ตัวอย่างที่ 4 <ใส่หัวข้อ> [เรียนรู้จาก](<ใส่ URL>)

In [ ]:
# ใส่ตัวอย่าง code ที่ได้เรียนรู้

1.4.5 ตัวอย่างที่ 5 <ใส่หัวข้อ> [เรียนรู้จาก](<ใส่ URL>)

In [ ]:
# ใส่ตัวอย่าง code ที่ได้เรียนรู้

# 2. การใช้งาน Numpy เบื้องต้น

*   [Numpy](https://www.w3schools.com/python/numpy/default.asp) เป็น Python library สำหรับการจัดการ array และการคำนวณคณิตศาสตร์
*   Numpy มีการจัดการ array และกลไกที่เรียกว่า vectorisztions ที่มีการใช้งาน hardware ของเครื่องเพื่อเพิ่มประสิทธิภาพในการคำนวณ Array ที่มีขนาดใหญ่ๆ



In [ ]:
import numpy as np
import time
from numpy import random


> 2.1 การสร้าง Vector ด้วย Numpy


*   ศึกษาการสร้าง Vector ด้วย methods ต่างๆ ของ Numpy


2.1.1 สร้าง vector 1 มิติที่มีขนาด 5 ตัว

In [ ]:
x=random.randint(100, size=(5))
print(x)

2.1.2 การสร้าง vector 2 มิติ

In [ ]:
# สร้าง vector 2 มิติ ขนาด 3 (rows) x5 (columns)
x = random.randint(100, size=(3, 5))
print(x)

# แสดงขนาดของ Array
print(x.shape)

2.1.3 ตัวอย่างการสร้าง Vector ด้วยฟังก์ชันอื่นๆ ของ Numpy

In [ ]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.zeros((4,));
print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.random_sample(4);
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);
print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

a = np.random.rand(4);
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

> 2.2 Numpy Operations

2.2.1 scalar + vector

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
c = 2
y = x + c
print(f"{x} + {c} = {y}")

2.2.2 Scalar + matrix

In [ ]:
X = np.array([[12, 76, 79, 80, 81],
            [81, 96, 3, 63, 17],
            [59,  6,  1, 24, 18]])
c = 2
Y = X + c
print(Y)

2.2.3 vector + vector

In [ ]:
x1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
x2 = np.array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
y = x1 + x2
print(y)

2.2.4 Vector + matrix

In [ ]:
X = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
v = np.array([1, 2, 3, 4])

Y = X + v
print(Y)

[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


2.2.5 Matrix + Metrix

In [ ]:
X1 = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
X2 = np.array([[1, 1, 1, 1],
              [2, 2, 2, 2],
              [3, 3, 3, 3]])
Y = X1 + X2
print(Y)


2.2.6 การเขียนโปรแกรมคำนวณ Dot Products

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
x = 0
for i in range(a.shape[0]):
  x = x + a[i] * b[i]

print(f"dot product = {x}")

2.2.7 การใช้ฟังก์ชั่น np.dot เพื่อคำนวณ Dot Products

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

x = np.dot(a, b)

print(f"dot product = {x}")


dot product = 95


2.2.8 การเรียบเทียบการคำนวณ dot product ด้วยวิธีธรรมดา และการใช้ Numpy

a. สร้าง function การคำนวณ dot product ด้วยวิธีทั่วไป

In [ ]:
def my_dot(a, b):
    """
   Compute the dot product of two vectors

    Args:
      a (ndarray (n,)):  input vector
      b (ndarray (n,)):  input vector with same dimension as a

    Returns:
      x (scalar):
    """
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

b. เปรียบเทียบเวลาในการคำนวณ

In [ ]:

np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 12.3603 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 4919.7960 ms 


> 2.3 ศึกษาเพิ่มเติม Numpy

*   ให้ นศ. เขียนตัวอย่าง code ที่ศึกษาด้วยตัวเองเพิ่มเติม อย่างน้อย 5 ตัวอย่าง



2.3.1 ตัวอย่างที่ 1 <ใส่หัวข้อ> [เรียนรู้จาก](<ใส่ URL>)

In [ ]:
# ใส่ตัวอย่าง code ที่ได้เรียนรู้

2.3.2 ตัวอย่างที่ 1 <ใส่หัวข้อ> [เรียนรู้จาก](<ใส่ URL>)

In [ ]:
# ใส่ตัวอย่าง code ที่ได้เรียนรู้

2.3.3 ตัวอย่างที่ 1 <ใส่หัวข้อ> [เรียนรู้จาก](<ใส่ URL>)

In [ ]:
# ใส่ตัวอย่าง code ที่ได้เรียนรู้

2.3.5 ตัวอย่างที่ 1 <ใส่หัวข้อ> [เรียนรู้จาก](<ใส่ URL>)

In [ ]:
# ใส่ตัวอย่าง code ที่ได้เรียนรู้

2.3.5 ตัวอย่างที่ 1 <ใส่หัวข้อ> [เรียนรู้จาก](<ใส่ URL>)

In [ ]:
# ใส่ตัวอย่าง code ที่ได้เรียนรู้